export const SET_INPUT_VALUE = 'SET_INPUT_VALUE';
export const ADD_CREDIT = "ADD_CREDIT";
export const GET_PENDDING_CREDITS = "GET_PENDDING_CREDITS";
export const GET_DENIES_CREDITS = "GET_DENIES_CREDITS";
export const GET_TOTAL_VALUE = 'GET_TOTAL_VALUE';
export const GET_CREDITS = 'GET_CREDITS';
export const ERROR = 'ERROR';
export const LOADING = 'LOADING';