export const SET_INPUT_VALUE = 'SET_INPUT_VALUE';
export const ADD_CREDIT = "ADD_CREDIT";
export const GET_ALL_CREDITS = "GET_ALL_CREDITS";
export const GET_DENIES_CREDITS = "GET_DENIES_CREDITS";
export const GET_PENDDING_CREDITS = "GET_DENIES_CREDITS";